name: 打包press博客

on:
  push:
    # push 代码的时候 哪个分支会受到影响 这里是 master 主分支
    branches:
      - master

# 推送之后执行一系列的任务
jobs:
  build:
    # 运行 ubuntu虚拟机系统
    runs-on: ubuntu-latest
    steps:
      # 获取代码
      - name: 迁出代码
        # 使用action库 action/checkout获取大妈
        uses: actions/checkout@master
      # 安装Node10

      - name: 安装node.js
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 14.18.0

      # 忽略版本
      - name: yarn set config
        run: yarn config set ignore-engines true
        
      - name: 安装yarn
        run: npm install -g yarn

      # 安装依赖
      - name: 安装依赖
        run: yarn

      # 打包
      - name: 打包
        run: yarn build

      # 上传到阿里云
      - name: 发布到阿里云
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          # 私钥 PRIVATE_KEY 要和 仓库的私钥名一致 也就是私钥名也要叫 PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          # SCP参数
          ARGS: '-avzr --delete'
          # 源目录 -- 打包后的文件目录，也就是这个文件会被传到服务器上.
          SOURCE: './public'
          # 服务器ip
          REMOTE_HOST: '121.40.166.6'
          # 用户
          REMOTE_USER: 'root'
          # 目标地址 -- 上传到服务器的地址
          TARGET: '/www/blog'
